version: "3.4"

services:
  backend:
    restart: "unless-stopped"
    image: blog
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:5000"
    environment:
      URI: $URI
      SCT: $SCT
      email: $email
      pass: $pass
      createdBy: $createdBy
